<a href="https://colab.research.google.com/github/fannyfagame-spec/NoteBook-Jupiter/blob/main/%5BJupyter_Notebooks_Youth%5D_Basic_Data_Operations_in_Pandas%202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size="+3">Module 33 - Basic Data Operations in Pandas</font>

In this notebook, we are going to discuss about:
- Descriptive Statistical Operations in Pandas: mean, median, mode, count, std, max, min, describe

## Reading a file

In [31]:
# Descriptive Statistical Operations on Data Frame
# Import Pandas Library
import pandas as pd

# Load Titanic Dataset as Dataframe
dataset = pd.read_csv('Datasets/train.csv')

# Show dataset
# head() bydefault show
# 5 rows of the dataframe
dataset.head()

,6,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.581,0.582,0.583,0.584,0.585,0.586,0.587,0.588,0.589,0.590
0,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,5,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Descriptive Statistical Operations

In [32]:
# dataset no. of columns and rows
dataset.shape

(19999, 785)

### mean

In [34]:
# Calculate mean
mean = dataset['Age'].mean()

# Print mean
print(mean)

KeyError: 'Age'

### median

In [ ]:
# Calculate Median of 'Fare' column
median = dataset['Fare'].median()

# Print median
print(median)

### mode

In [ ]:
# Calculate Mode of 'Sex' column
mode = dataset['Sex'].mode()

# Print mode
print(mode)

### Count

In [ ]:
# Calculate Count of 'Ticket' column
count = dataset['Ticket'].count()

# Print count
print(count)

### Standard Deviation

In [ ]:
# Calculate Standard Deviation
# of 'Fare' column
std = dataset['Fare'].std()

# Print standard deviation
print(std)

### maximum value

In [ ]:
# Calculate Maximum value in 'Age' column
maxValue = dataset['Age'].max()

# Print maxValue
print(maxValue)

### minimum value

In [ ]:
# Calculate Minimum value in 'Fare' column
minValue = dataset['Fare'].min()

# Print minValue
print(minValue)

### describe statistical summary

In [ ]:
# Statistical summary
dataset.describe()

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Statistical Operations </p>**

In [ ]:
## Read the file Datasets/iris.csv. Print the dataframe. From the csv file calculate the following:
# head()
# tail()
# shape of the dataset
# mean of the sepal_length
# median of the petal_length
# statistical summary

In [35]:
# Read file
dataset = pd.read_csv('Datasets/iris.csv')

# Print dataframe
print(dataset)

# head()
dataset.head()
# tail()
dataset.tail()
# shape
dataset.shape
# mean of sepal_length
mean = dataset['sepal_length'].mean()
print(mean)
# median of petal_length
median = dataset['petal_length'].median()
print(median)
# statistical summary
dataset.describe()

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
5            5.4          3.9           1.7          0.4      setosa
6            4.6          3.4           1.4          0.3      setosa
7            5.0          3.4           1.5          0.2      setosa
8            4.4          2.9           1.4          0.2      setosa
9            4.9          3.1           1.5          0.1      setosa
10           5.8          2.7           5.1          1.9  versicolor
11           6.3          2.9           5.6          1.8  versicolor
12           6.5          3.0           5.8          2.2  versicolor
13           7.6          3.0           6.6          2.1  versicolor
14           4.9          2.5           4.5          1.7  versicolor
15           6.1          2.8           4.7          1.2  versicolor
16           6.4          2.9           4.3          1.3  versicolor
17           6.6          3.0           4.4          1.4  versicolor
18           6.8          2.8           4.8          1.4  versicolor
19           6.7          3.0           5.0          1.7  versicolor
20           6.3          3.3           6.0          2.5   virginica
21           5.8          2.7           5.1          1.9   virginica
22           7.1          3.0           5.9          2.1   virginica
23           6.3          2.9           5.6          1.8   virginica
24           6.5          3.0           5.8          2.2   virginica
25           7.6          3.0           6.6          2.1   virginica
26           7.3          2.9           6.3          1.8   virginica
27           6.7          2.5           5.8          1.8   virginica
28           7.2          3.6           6.1          2.5   virginica
29           6.5          3.2           5.1          2.0   virginica
5.9866666666666655
4.9

       sepal_length  sepal_width  petal_length  petal_width
count     30.000000    30.000000     30.000000    30.000000
mean       5.986667     3.060000      4.120000     1.320000
std        0.976882     0.321205      2.005406     0.844618
min        4.400000     2.500000      1.300000     0.100000
25%        5.000000     2.900000      1.500000     0.225000
50%        6.300000     3.000000      4.900000     1.700000
75%        6.675000     3.200000      5.800000     1.975000
max        7.600000     3.900000      6.600000     2.500000